// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonZp8w9vOYr-eOivCCic1NKFjk6d6Htg',
    appId: '1:1002931568183:web:3585fcf632f84d653ec9b2',
    messagingSenderId: '1002931568183',
    projectId: 'taekwondodatabase-f89aa',
    authDomain: 'taekwondodatabase-f89aa.firebaseapp.com',
    storageBucket: 'taekwondodatabase-f89aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLX-TNVATfbE0_1WCLtejjcFAjhr-XN5I',
    appId: '1:1002931568183:android:599c7a023dc138d33ec9b2',
    messagingSenderId: '1002931568183',
    projectId: 'taekwondodatabase-f89aa',
    storageBucket: 'taekwondodatabase-f89aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClz_84B49S8Weh4XQcYfSwsl7FWmEkVt8',
    appId: '1:1002931568183:ios:abc9b0db8ae71dfa3ec9b2',
    messagingSenderId: '1002931568183',
    projectId: 'taekwondodatabase-f89aa',
    storageBucket: 'taekwondodatabase-f89aa.appspot.com',
    iosClientId: '1002931568183-2vf0cvlr6pooi3flp381ri3ob83l83jo.apps.googleusercontent.com',
    iosBundleId: 'com.truemartialarts.tmaInstructors',
  );
}
